package assignment;

import javax.swing.*;
import java.sql.*;

public class Registerstudent extends javax.swing.JFrame {
   
   
    public Registerstudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jReturnButton1 = new javax.swing.JButton();
        stuaddress = new javax.swing.JTextField();
        studate = new com.toedter.calendar.JDateChooser();
        stupassword = new javax.swing.JPasswordField();
        stuid = new javax.swing.JTextField();
        stuname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 560));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 450, 83, 36);

        jReturnButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jReturnButton1.setText("Cancel");
        jReturnButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jReturnButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jReturnButton1);
        jReturnButton1.setBounds(310, 450, 75, 36);

        stuaddress.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        stuaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuaddressActionPerformed(evt);
            }
        });
        getContentPane().add(stuaddress);
        stuaddress.setBounds(220, 350, 273, 90);

        studate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        getContentPane().add(studate);
        studate.setBounds(220, 290, 272, 40);

        stupassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        stupassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stupasswordActionPerformed(evt);
            }
        });
        getContentPane().add(stupassword);
        stupassword.setBounds(220, 230, 272, 40);

        stuid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        stuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuidActionPerformed(evt);
            }
        });
        getContentPane().add(stuid);
        stuid.setBounds(220, 170, 273, 40);

        stuname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        stuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stunameActionPerformed(evt);
            }
        });
        getContentPane().add(stuname);
        stuname.setBounds(220, 110, 273, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register Student Account Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 40, 380, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 110, 90, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Student ID:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(102, 170, 100, 45);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 230, 90, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Birth Date:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 290, 110, 36);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Address:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 360, 80, 25);

        jPanel1.setBackground(java.awt.Color.gray);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 40, 360, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/abstract-background-1061121_640.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-6, -6, 640, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Connection con;
        Connectiondatabase Rcon = new Connectiondatabase();
        con = Rcon.getConnection();
        String query = "insert into student (name, id, password, birthdate, address) values (?, ?, ?, ?, ?)";
        try{
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, stuname.getText());
            pst.setString(2, stuid.getText());
            pst.setString(3, new String(stupassword.getPassword()));
            pst.setString(4, ((JTextField)studate.getDateEditor().getUiComponent()).getText());
            pst.setString(5, stuaddress.getText());
            JOptionPane.showMessageDialog(null, "REGISTER SUCCESSFULLY");
            pst.executeUpdate();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"REGISTER FAILED"+ ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stuaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuaddressActionPerformed

    private void stuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuidActionPerformed

    private void stupasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stupasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stupasswordActionPerformed

    private void jReturnButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jReturnButton1MouseClicked
        adminmenu am = new adminmenu();
        am.setVisible(true);
        am.pack();
        am.setLocationRelativeTo(null);
        am.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jReturnButton1MouseClicked

    private void stunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stunameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registerstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registerstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registerstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registerstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registerstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jReturnButton1;
    private javax.swing.JTextField stuaddress;
    private com.toedter.calendar.JDateChooser studate;
    private javax.swing.JTextField stuid;
    private javax.swing.JTextField stuname;
    private javax.swing.JPasswordField stupassword;
    // End of variables declaration//GEN-END:variables
}
