/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author User
 */
public class Registercourse extends javax.swing.JFrame {

    /**
     * Creates new form Registercourse
     */
    public Registercourse() {
        initComponents();
        student();
        instructor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        couname = new javax.swing.JTextField();
        couid = new javax.swing.JTextField();
        insname = new javax.swing.JComboBox<>();
        stuname = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 570));
        getContentPane().setLayout(null);

        couname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        getContentPane().add(couname);
        couname.setBounds(280, 140, 228, 40);

        couid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        getContentPane().add(couid);
        couid.setBounds(280, 200, 228, 40);

        insname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        insname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insnameActionPerformed(evt);
            }
        });
        getContentPane().add(insname);
        insname.setBounds(280, 260, 228, 40);

        stuname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        getContentPane().add(stuname);
        stuname.setBounds(280, 320, 228, 36);

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton3.setText("Create");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(410, 400, 100, 50);

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 400, 100, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Select Student:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 320, 126, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Select Instructor:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 260, 141, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Course ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 210, 110, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Course Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 150, 120, 22);

        jPanel1.setBackground(java.awt.Color.gray);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Create Course Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(170, 40, 290, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/abstract-background-1061121_640.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-6, -6, 640, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        adminmenu am = new adminmenu();
        am.setVisible(true);
        am.pack();
        am.setLocationRelativeTo(null);
        am.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Connection con;
        Connectiondatabase Rcon = new Connectiondatabase();
        con = Rcon.getConnection();
        String query = "insert into course (name, id, instructorid, studentid) values (?, ?, ?, ?)";
        try{
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, couname.getText());
            pst.setString(2, couid.getText());
            pst.setString(3, insname.getSelectedItem().toString());
            pst.setString(4, stuname.getSelectedItem().toString());
            JOptionPane.showMessageDialog(null, "Create SUCCESSFULLY");
            pst.executeUpdate();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Create FAILED"+ ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void insnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insnameActionPerformed
        
    }//GEN-LAST:event_insnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registercourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registercourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registercourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registercourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registercourse().setVisible(true);
            }
        });
    }
    
       private void student(){
        try{
        Connection con;
        Connectiondatabase Rcon = new Connectiondatabase();
        con = Rcon.getConnection();
        String query = "select * from student";
        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();
        while(rs.next())
        {
            String studentname = rs.getString("name");
            stuname.addItem(studentname);
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"REGISTER FAILED"+ ex);
        }
    }
       
        private void instructor(){
        try{
        Connection con;
        Connectiondatabase Rcon = new Connectiondatabase();
        con = Rcon.getConnection();
        String query = "select * from instructor";
        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();
        while(rs.next())
        {
            String instructortname = rs.getString("name");
            insname.addItem(instructortname);
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"REGISTER FAILED"+ ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField couid;
    private javax.swing.JTextField couname;
    private javax.swing.JComboBox<String> insname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> stuname;
    // End of variables declaration//GEN-END:variables
}
